# Generated by Django 5.2.17 on 2026-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="exige_aprovacao_vaga",
            field=models.BooleanField(default=True),
        ),
    ]
