# Generated by Django 5.2.17 on 2026-09-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_exige_aprovacao_vaga"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="exige_aprovacao_vaga",
        ),
    ]
