# Generated by Django 5.2.17 on 2026-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_company_exige_aprovacao_vaga"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_confirmado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
