# Generated by Django 5.2.17 on 2026-09-09 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_company_exige_aprovacao_vaga"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=60)),
                ("cor", models.CharField(blank=True, default="", max_length=20, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "unique_together": {("company", "nome")},
            },
        ),
    ]
