# Generated by Django 5.2.17 on 2026-09-09 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_company_exige_aprovacao_vaga"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("verbo", models.CharField(max_length=50)),
                (
                    "alvo_tipo",
                    models.CharField(
                        choices=[("VAGA", "Vaga"), ("CANDIDATO", "Candidato")], max_length=20
                    ),
                ),
                ("alvo_id", models.UUIDField()),
                ("resumo", models.CharField(max_length=255)),
                ("dados", models.JSONField(blank=True, default=dict)),
                (
                    "ator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "alvo_tipo", "alvo_id"],
                        name="atividade_a_company_8614f2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "alvo_tipo",
                    models.CharField(
                        choices=[("VAGA", "Vaga"), ("CANDIDATO", "Candidato")], max_length=20
                    ),
                ),
                ("alvo_id", models.UUIDField()),
                ("texto", models.TextField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="accounts.company",
                    ),
                ),
                (
                    "mencoes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comentarios_mencionado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "alvo_tipo", "alvo_id"],
                        name="atividade_c_company_76b611_idx",
                    )
                ],
            },
        ),
    ]
