# Generated by Django 5.2.17 on 2026-09-09 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_exige_aprovacao_vaga"),
        ("vagas", "0002_vaganotificacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="aprovada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="aprovada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vagas_aprovadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="cobrada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="data_alvo_preenchimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="data_inicio_prevista",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="encerrada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="fechada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="motivo_recusa",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="vaga",
            name="motivo_solicitacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUMENTO_QUADRO", "Aumento de quadro"),
                    ("SUBSTITUICAO", "Substituição"),
                    ("PROJETO", "Projeto novo"),
                    ("OUTRO", "Outro"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="prioridade",
            field=models.IntegerField(choices=[(1, "Baixa"), (2, "Média"), (3, "Alta")], default=2),
        ),
        migrations.AddField(
            model_name="vaga",
            name="publicada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="recusada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="solicitada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("SOLICITADA", "Solicitada"),
                    ("RECUSADA", "Recusada"),
                    ("APROVADA", "Aprovada"),
                    ("PUBLICADA", "Publicada"),
                    ("RECEBENDO", "Recebendo candidaturas"),
                    ("ENCERRADA", "Candidaturas encerradas"),
                    ("EM_TRIAGEM", "Em triagem"),
                    ("CONGELADA", "Congelada"),
                    ("CANCELADA", "Cancelada"),
                    ("PREENCHIDA", "Preenchida"),
                ],
                default="RASCUNHO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="status_pre_congelamento",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="vaga",
            name="total_cobrancas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vaga",
            name="triagem_iniciada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaga",
            name="urgente",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="VagaCobranca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("status_no_momento", models.CharField(max_length=20)),
                ("mensagem", models.CharField(blank=True, default="", max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaga_cobrancas",
                        to="accounts.company",
                    ),
                ),
                (
                    "de_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "para_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas_recebidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobrancas",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VagaHistoricoStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("de_status", models.CharField(blank=True, default="", max_length=20)),
                ("para_status", models.CharField(max_length=20)),
                ("observacao", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaga_historicos",
                        to="accounts.company",
                    ),
                ),
                (
                    "por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaga_transicoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
