# Generated by Django 5.2.17 on 2026-09-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0004_backfill_status_vaga"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapakanban",
            name="exige_cadastro_completo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vaga",
            name="etapa_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vagas_na_etapa",
                to="vagas.etapakanban",
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="qtd_pessoas_fase",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
