# Generated by Django 5.2.17 on 2026-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0006_backfill_exige_cadastro_e_etapa_vaga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("SOLICITADA", "Solicitada"),
                    ("RECUSADA", "Recusada"),
                    ("APROVADA", "Aprovada"),
                    ("PUBLICADA", "Publicada"),
                    ("ENCERRADA", "Candidaturas encerradas"),
                    ("EM_TRIAGEM", "Em triagem"),
                    ("CONGELADA", "Congelada"),
                    ("CANCELADA", "Cancelada"),
                    ("PREENCHIDA", "Preenchida"),
                ],
                default="RASCUNHO",
                max_length=20,
            ),
        ),
    ]
