# Generated by Django 5.2.17 on 2026-09-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0008_backfill_recebendo_para_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="prazo_alertado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
