# Generated by Django 5.2.17 on 2026-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("vagas", "0009_vaga_prazo_alertado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="vagas", to="tags.tag"),
        ),
    ]
