# Generated by Django 5.2.17 on 2026-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0011_vaga_responsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaganotificacao",
            name="lida_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
