# Generated by Django 5.2.17 on 2026-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0012_vaganotificacao_lida_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="codigo_email",
            field=models.SlugField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="vaga",
            name="is_banco_talentos",
            field=models.BooleanField(default=False),
        ),
    ]
