# Generated by Django 5.2.17 on 2026-09-14 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_company_exige_aprovacao_vaga"),
        ("candidatos", "0011_merge_20260914_1134"),
        ("vagas", "0013_vaga_codigo_email_vaga_is_banco_talentos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaixaEntradaEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("host", models.CharField(max_length=255)),
                ("porta", models.PositiveIntegerField(default=993)),
                ("usar_ssl", models.BooleanField(default=True)),
                ("usuario", models.CharField(max_length=255)),
                ("senha_cifrada", models.CharField(blank=True, default="", max_length=500)),
                ("pasta", models.CharField(default="INBOX", max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("ultima_verificacao_em", models.DateTimeField(blank=True, null=True)),
                ("ultimo_erro", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caixa_entrada_email",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidatoTriagemIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("email_remetente", models.EmailField(blank=True, default="", max_length=254)),
                ("nome_remetente", models.CharField(blank=True, default="", max_length=255)),
                ("assunto_email", models.CharField(blank=True, default="", max_length=500)),
                ("message_id", models.CharField(max_length=998)),
                ("curriculo_key", models.CharField(blank=True, default="", max_length=500)),
                (
                    "curriculo_content_type",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("nome_extraido", models.CharField(blank=True, default="", max_length=255)),
                ("email_extraido", models.CharField(blank=True, default="", max_length=255)),
                ("telefone_extraido", models.CharField(blank=True, default="", max_length=30)),
                ("cpf_extraido", models.CharField(blank=True, default="", max_length=20)),
                ("linkedin_extraido", models.CharField(blank=True, default="", max_length=500)),
                ("perfil_formacao", models.TextField(blank=True, default="")),
                ("perfil_experiencia", models.TextField(blank=True, default="")),
                ("perfil_habilidades", models.TextField(blank=True, default="")),
                ("perfil_certificacoes", models.TextField(blank=True, default="")),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("justificativa_ia", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("PRONTO", "Pronto"),
                            ("ERRO", "Erro"),
                            ("RESOLVIDO", "Resolvido"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("erro_detalhe", models.TextField(blank=True, default="")),
                ("tentativas", models.PositiveSmallIntegerField(default=0)),
                ("resolvido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "candidato_resultante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origem_triagem_ia",
                        to="candidatos.candidato",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triagens_ia",
                        to="accounts.company",
                    ),
                ),
                (
                    "resolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triagens_ia_resolvidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triagens_ia",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "message_id"),
                        name="unique_triagem_ia_message_id_por_company",
                    )
                ],
            },
        ),
    ]
