# Generated by Django 5.2.17 on 2026-09-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triagem_ia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caixaentradaemail",
            name="google_refresh_token_cifrado",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="caixaentradaemail",
            name="provider",
            field=models.CharField(
                choices=[("IMAP", "IMAP manual"), ("GOOGLE", "Google (Gmail)")],
                default="IMAP",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="caixaentradaemail",
            name="host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
