# Generated by Django 5.2.17 on 2026-09-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_company_exige_aprovacao_vaga"),
        ("triagem_ia", "0002_caixaentradaemail_google_refresh_token_cifrado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixaentradaemail",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caixas_entrada_email",
                to="accounts.company",
            ),
        ),
    ]
