# Generated by Django 5.2.17 on 2026-09-04 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('cpf', models.CharField(blank=True, default='', max_length=20)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('curriculo_key', models.CharField(max_length=500)),
                ('curriculo_content_type', models.CharField(default='application/pdf', max_length=100)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='accounts.company')),
            ],
            options={
                'ordering': ['ordem', '-created_at'],
            },
        ),
    ]
