# Generated by Django 5.2.17 on 2026-09-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='etapa_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='vagas.etapakanban'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vagas.vaga'),
        ),
    ]
