# Generated by Django 5.2.17 on 2026-09-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="resumo_perfil",
            field=models.TextField(blank=True, default=""),
        ),
    ]
