# Generated by Django 5.2.17 on 2026-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0003_candidato_resumo_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidato",
            name="resumo_perfil",
        ),
        migrations.AddField(
            model_name="candidato",
            name="perfil_certificacoes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="candidato",
            name="perfil_experiencia",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="candidato",
            name="perfil_formacao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="candidato",
            name="perfil_habilidades",
            field=models.TextField(blank=True, default=""),
        ),
    ]
