# Generated by Django 5.2.17 on 2026-09-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0005_candidatonotificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="reprovado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
