# Generated by Django 5.2.17 on 2026-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0006_candidato_reprovado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="curriculo_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
