# Generated by Django 5.2.17 on 2026-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0007_alter_candidato_curriculo_key"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="candidatos", to="tags.tag"),
        ),
    ]
