# Generated by Django 5.2.17 on 2026-09-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0009_candidato_responsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="motivo_reprovacao",
            field=models.TextField(blank=True, default=""),
        ),
    ]
