# Generated by Django 5.2.17 on 2026-09-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0010_candidato_motivo_reprovacao"),
        ("candidatos", "0010_candidatonotificacao_lida_em"),
    ]

    operations = []
