# Generated by Django 5.2.17 on 2026-09-09 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_exige_aprovacao_vaga"),
        ("candidatos", "0007_alter_candidato_curriculo_key"),
        ("chat", "0002_chatleitura"),
        ("vagas", "0006_backfill_exige_cadastro_e_etapa_vaga"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatleitura",
            name="unique_leitura_usuario_candidato",
        ),
        migrations.AddField(
            model_name="chatleitura",
            name="vaga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leituras",
                to="vagas.vaga",
            ),
        ),
        migrations.AddField(
            model_name="chatmensagem",
            name="vaga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens",
                to="vagas.vaga",
            ),
        ),
        migrations.AlterField(
            model_name="chatleitura",
            name="candidato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leituras",
                to="candidatos.candidato",
            ),
        ),
        migrations.AlterField(
            model_name="chatmensagem",
            name="candidato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens",
                to="candidatos.candidato",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatleitura",
            constraint=models.UniqueConstraint(
                condition=models.Q(("candidato__isnull", False)),
                fields=("usuario", "candidato"),
                name="unique_leitura_usuario_candidato",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatleitura",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vaga__isnull", False)),
                fields=("usuario", "vaga"),
                name="unique_leitura_usuario_vaga",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmensagem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("candidato__isnull", False), ("vaga__isnull", True)),
                    models.Q(("candidato__isnull", True), ("vaga__isnull", False)),
                    _connector="OR",
                ),
                name="chatmensagem_candidato_xor_vaga",
            ),
        ),
    ]
